# Cache bust: 2026-01-27-v2
[phases.setup]
nixPkgs = ["nodejs_20", "chromium"]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/nix/var/nix/profiles/default/bin/chromium"
