[phases.setup]
aptPkgs = ["chromium", "fonts-liberation", "libnss3", "libatk-bridge2.0-0", "libxkbcommon0", "libgbm1"]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
